[package]
name = "ssip-server"
version = "0.1.0"
authors = ["Boni Lindsley <boni.lindsley@gmail.com>"]
edition = "2018"

[dependencies]
cpal = "*"
tokio = { version = "*", features = ["io-util", "net", "rt"] }
ttspico = "*"
